/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Parts;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Elvin
 */
public class ChangeParts extends javax.swing.JInternalFrame {
    String q ="";
    String w ="";
    String e = "";
    int option = 0;
    int vn = 0;
    int number =0;
    double secNumber = 0;
    int t =0;
    int p =0;
    String str1 ="";
    String str2 ="";
    String str3 = "";
    String not = " ";
    /**
     * Creates new form ChangeParts
     */
    public ChangeParts() {
        initComponents();
        try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
        Statement sqlStatement = con.createStatement();
        ResultSet sqlResult = sqlStatement.executeQuery("SELECT Number FROM Market.Parts"))
        {
            
            while(sqlResult.next())
                jComboBox1.addItem(sqlResult.getString(1));
            
        
        }
        catch(SQLException sqlEx)
        {
            JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Part Change");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("onHand:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Change Name");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Change Price");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Change onHand");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Change All");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Cancel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText(vn + " Changes made");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        option = 0;
        jTextArea1.setEditable(false);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jComboBox1.removeAllItems();
        
        try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
        Statement sqlStatement = con.createStatement();
        ResultSet sqlResult = sqlStatement.executeQuery("SELECT Number FROM Market.Parts"))
        {
            
            while(sqlResult.next())
                jComboBox1.addItem(sqlResult.getString(1));
            
        
        }
        catch(SQLException sqlEx)
        {
            JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        jComboBox1.setSelectedIndex(-1);
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        option = 1;
        jTextArea1.setText("");
        jTextArea1.setEditable(true);
        jTextField1.setEditable(false);
        jTextField1.setText(w);
        jTextField2.setEditable(false);
        jTextField2.setText(e);
        t=0;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        option = 2;
        jTextArea1.setEditable(false);
        jTextArea1.setText(q);
        jTextField1.setText("");
        jTextField1.setEditable(true);
        jTextField2.setText(e);
        jTextField2.setEditable(false);
        t=0;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        option = 3;
        jTextArea1.setEditable(false);
        jTextArea1.setText(q);
        jTextField1.setEditable(false);
        jTextField1.setText(w);
        jTextField2.setText("");
        jTextField2.setEditable(true);
        t=0;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        option = 4;
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setEditable(true);
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
        t=0;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        vn = 0;
        option = 0;
        jLabel5.setText(vn + " Changes made");
        jTextArea1.setEditable(false);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedIndex()== -1 || jComboBox1.getSelectedItem().equals("Select"))
        {
            jTextArea1.setEditable(false);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
         jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        }
         else
         {
            jTextArea1.setEditable(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
            Statement sqlStatement = con.createStatement();
            ResultSet sqlResult = sqlStatement.executeQuery("SELECT * FROM Market.Parts WHERE Number = '"+ jComboBox1.getSelectedItem() + "'"))
            {
                while(sqlResult.next())
                {
                    jTextArea1.setText(sqlResult.getString(2));
                    q =sqlResult.getString(2);
                    jTextField1.setText(sqlResult.getString(3));
                    w = sqlResult.getString(3);
                    jTextField2.setText(sqlResult.getString(4));
                    e = sqlResult.getString(4);
                }


            }
            catch(SQLException sqlEx)
            {
                JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
         }
        t=0;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == -1 || jComboBox1.getSelectedItem() == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select a Number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextArea1.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Name can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (jTextField1.getText().trim().equals("")|| jTextField2.getText().trim().equals("") ||Integer.parseInt(jTextField2.getText()) <= 0 || Double.parseDouble(jTextField1.getText()) <= 0)
        {
            JOptionPane.showMessageDialog(null, "onHand and Price must be greater than 0", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(option == 1)
            {
                
                    try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Parts SET Name = '" + jTextArea1.getText() +"' WHERE Number = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vn++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
               jComboBox1.setSelectedIndex(-1);
               jTextArea1.setEditable(false);
               jTextField1.setEditable(false);
               jTextField2.setEditable(false);
               jTextArea1.setText("");
               jTextField1.setText("");
               jTextField2.setText("");
               
            }
            else if (option == 2)
            {
               
                
                    try
                   {
                   number = Integer.parseInt(jTextField1.getText());
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Parts SET Price = " + jTextField1.getText() +" WHERE Number = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vn++;
                   }
                    catch (NumberFormatException e)
                   {
                       JOptionPane.showMessageDialog(null, "Price needs to be a double & onHand need an integer", "Error", JOptionPane.ERROR_MESSAGE);
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
               jComboBox1.setSelectedIndex(-1);
               jTextArea1.setEditable(false);
               jTextField1.setEditable(false);
               jTextField2.setEditable(false);
               jTextArea1.setText("");
               jTextField1.setText("");
               jTextField2.setText("");
                
            }
            else if (option == 3)
            {
                
                    try
                   {
                   secNumber = Integer.parseInt(jTextField2.getText());
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Parts SET onHand = " + jTextField2.getText() +" WHERE Number = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vn++;
                   }
                    catch (NumberFormatException e)
                   {
                       JOptionPane.showMessageDialog(null, "Price needs to be a double & onHand need an integer", "Error", JOptionPane.ERROR_MESSAGE);
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
               jComboBox1.setSelectedIndex(-1);
               jTextArea1.setEditable(false);
               jTextField1.setEditable(false);
               jTextField2.setEditable(false);
               jTextArea1.setText("");
               jTextField1.setText("");
               jTextField2.setText("");
                
            }
            else if (option == 4)
            {
                 
                try
                {
                number = Integer.parseInt(jTextField1.getText());
                secNumber = Integer.parseInt(jTextField2.getText());
                Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                sqlStatement.executeUpdate("UPDATE Market.Parts SET onHand = " + jTextField2.getText() + ", Price = " + jTextField1.getText() + ", Name = '" + jTextArea1.getText() + "' WHERE Number = '" + jComboBox1.getSelectedItem()+ "'");
                sqlStatement.close();
                vn++;
                }
                 catch (NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Price needs to be a double & onHand need an integer", "Error", JOptionPane.ERROR_MESSAGE);
                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            jComboBox1.setSelectedIndex(-1);
            jTextArea1.setEditable(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextArea1.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
               
            }
            else
            {
            jComboBox1.setSelectedIndex(-1);
            jTextArea1.setEditable(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextArea1.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
            JOptionPane.showMessageDialog(null, "No changes made", "Notice", JOptionPane.INFORMATION_MESSAGE);
            }
            jLabel5.setText(vn + " Changes made");
            q="";
            w="";
            e="";
        }
        p = 0;
        t =0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            t--;
            if(t < 0)
                t=0;
        }
        if(t < 11)
        {
            if (Character.isDigit(c)|| c == '.')
            {
                t++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        char c2 = evt.getKeyChar();
        if(c2 == KeyEvent.VK_BACK_SPACE)
        {
            p--;
            if(p < 0)
                p=0;
        }
        else if(p < 200)
        {
            
            p++;
        }
        else if (p >= 200)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
