/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Customer.*;
import GUI.Parts.*;
import GUI.Purchases.*;
import GUI.Store.*;
import Reports.*;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Elvin
 */
public class MainFrame extends javax.swing.JFrame {
AboutFrame about;
StoreDeletion storeDeleteFrame;
StoreNew storeNewFrame;
NewParts newPartsFrame;
ChangeParts changePartsFrame;
DeleteParts deletePartsFrame;
CustomerAdd NewCustomerFrame;
CustomerDelete DeleteCustomer;
CustomerChange CustomerChangeFrame;
PurchasesNew PurchaseAdd;
PurchasesDelete PurchaseDeletion;
MainReport myMainReport;
PurchasesReport myPurchasesReport;
CustomerReport myCustomerReport;
Continue con;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setSize(1300,800);
        try
    {
      Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
    
    }
    catch(SQLException sqlEx)
    {
            con = new Continue(this, true);
            con.setVisible(true);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuInventory = new javax.swing.JMenu();
        jMenuStore = new javax.swing.JMenu();
        jMenuItemStoreNew = new javax.swing.JMenuItem();
        jMenuItemStoreDelete = new javax.swing.JMenuItem();
        jMenuParts = new javax.swing.JMenu();
        jMenuItemPartsNew = new javax.swing.JMenuItem();
        jMenuItemPartsChange = new javax.swing.JMenuItem();
        jMenuItemPartsDelete = new javax.swing.JMenuItem();
        jMenuCustomer = new javax.swing.JMenu();
        jMenuItemCustomerNew = new javax.swing.JMenuItem();
        jMenuItemCustomerChange = new javax.swing.JMenuItem();
        jMenuItemCustomerDelete = new javax.swing.JMenuItem();
        jMenuPurchases = new javax.swing.JMenu();
        jMenuPurchasesPOS = new javax.swing.JMenu();
        jMenuItemPOSAdd = new javax.swing.JMenuItem();
        jMenuItemPOSDelete = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuInventory.setText("Inventory");

        jMenuStore.setText("Store");

        jMenuItemStoreNew.setText("New");
        jMenuItemStoreNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStoreNewActionPerformed(evt);
            }
        });
        jMenuStore.add(jMenuItemStoreNew);

        jMenuItemStoreDelete.setText("Delete");
        jMenuItemStoreDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStoreDeleteActionPerformed(evt);
            }
        });
        jMenuStore.add(jMenuItemStoreDelete);

        jMenuInventory.add(jMenuStore);

        jMenuParts.setText("Parts");

        jMenuItemPartsNew.setText("New");
        jMenuItemPartsNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartsNewActionPerformed(evt);
            }
        });
        jMenuParts.add(jMenuItemPartsNew);

        jMenuItemPartsChange.setText("Change");
        jMenuItemPartsChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartsChangeActionPerformed(evt);
            }
        });
        jMenuParts.add(jMenuItemPartsChange);

        jMenuItemPartsDelete.setText("Delete");
        jMenuItemPartsDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartsDeleteActionPerformed(evt);
            }
        });
        jMenuParts.add(jMenuItemPartsDelete);

        jMenuInventory.add(jMenuParts);

        jMenuBar1.add(jMenuInventory);

        jMenuCustomer.setText("Customer");

        jMenuItemCustomerNew.setText("New");
        jMenuItemCustomerNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerNewActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemCustomerNew);

        jMenuItemCustomerChange.setText("Change");
        jMenuItemCustomerChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerChangeActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemCustomerChange);

        jMenuItemCustomerDelete.setText("Delete");
        jMenuItemCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerDeleteActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jMenuItemCustomerDelete);

        jMenuBar1.add(jMenuCustomer);

        jMenuPurchases.setText("Purchases");

        jMenuPurchasesPOS.setText("POS");

        jMenuItemPOSAdd.setText("Add");
        jMenuItemPOSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPOSAddActionPerformed(evt);
            }
        });
        jMenuPurchasesPOS.add(jMenuItemPOSAdd);

        jMenuItemPOSDelete.setText("Delete");
        jMenuItemPOSDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPOSDeleteActionPerformed(evt);
            }
        });
        jMenuPurchasesPOS.add(jMenuItemPOSDelete);

        jMenuPurchases.add(jMenuPurchasesPOS);

        jMenuBar1.add(jMenuPurchases);

        jMenu1.setText("Report");

        jMenuItem1.setText("Inventory Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Purchases Report");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Customer Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemPartsChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartsChangeActionPerformed
        // TODO add your handling code here:
        changePartsFrame = new ChangeParts();
        Desktop.add(changePartsFrame);
        changePartsFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemPartsChangeActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        if(about == null)
        {
            about = new AboutFrame(this,true);
            about.setSize(600, 345);
            about.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void jMenuItemStoreDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStoreDeleteActionPerformed
        // TODO add your handling code here:
            storeDeleteFrame = new StoreDeletion();
            Desktop.add(storeDeleteFrame);
            storeDeleteFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemStoreDeleteActionPerformed

    private void jMenuItemStoreNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStoreNewActionPerformed
        // TODO add your handling code here:
        storeNewFrame = new StoreNew();
        Desktop.add(storeNewFrame);
        storeNewFrame.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemStoreNewActionPerformed

    private void jMenuItemPartsNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartsNewActionPerformed
        // TODO add your handling code here:
        newPartsFrame = new NewParts();
        Desktop.add(newPartsFrame);
        newPartsFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemPartsNewActionPerformed

    private void jMenuItemPartsDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartsDeleteActionPerformed
        // TODO add your handling code here:
        deletePartsFrame = new DeleteParts();
        Desktop.add(deletePartsFrame);
        deletePartsFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemPartsDeleteActionPerformed

    private void jMenuItemCustomerNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerNewActionPerformed
        // TODO add your handling code here:
        NewCustomerFrame = new CustomerAdd();
        Desktop.add(NewCustomerFrame);
        NewCustomerFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustomerNewActionPerformed

    private void jMenuItemCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerDeleteActionPerformed
        // TODO add your handling code here:
        DeleteCustomer = new CustomerDelete();
        Desktop.add(DeleteCustomer);
        DeleteCustomer.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustomerDeleteActionPerformed

    private void jMenuItemCustomerChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerChangeActionPerformed
        // TODO add your handling code here:
        CustomerChangeFrame = new CustomerChange();
        Desktop.add(CustomerChangeFrame);
        CustomerChangeFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustomerChangeActionPerformed

    private void jMenuItemPOSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPOSAddActionPerformed
        // TODO add your handling code here:
        PurchaseAdd = new PurchasesNew();
        Desktop.add(PurchaseAdd);
        PurchaseAdd.setVisible(true);
    }//GEN-LAST:event_jMenuItemPOSAddActionPerformed

    private void jMenuItemPOSDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPOSDeleteActionPerformed
        // TODO add your handling code here:
        PurchaseDeletion = new PurchasesDelete();
        Desktop.add(PurchaseDeletion);
        PurchaseDeletion.setVisible(true);
    }//GEN-LAST:event_jMenuItemPOSDeleteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        myMainReport = new MainReport(this,true);
        myMainReport.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        myMainReport.setSize(585,300);
        myMainReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         myPurchasesReport = new PurchasesReport(this,true);
        myPurchasesReport.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        myPurchasesReport.setSize(585,300);
        myPurchasesReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        myCustomerReport = new CustomerReport(this,true);
        myCustomerReport.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        myCustomerReport.setSize(585,300);
        myCustomerReport.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCustomer;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuInventory;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCustomerChange;
    private javax.swing.JMenuItem jMenuItemCustomerDelete;
    private javax.swing.JMenuItem jMenuItemCustomerNew;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPOSAdd;
    private javax.swing.JMenuItem jMenuItemPOSDelete;
    private javax.swing.JMenuItem jMenuItemPartsChange;
    private javax.swing.JMenuItem jMenuItemPartsDelete;
    private javax.swing.JMenuItem jMenuItemPartsNew;
    private javax.swing.JMenuItem jMenuItemStoreDelete;
    private javax.swing.JMenuItem jMenuItemStoreNew;
    private javax.swing.JMenu jMenuParts;
    private javax.swing.JMenu jMenuPurchases;
    private javax.swing.JMenu jMenuPurchasesPOS;
    private javax.swing.JMenu jMenuStore;
    // End of variables declaration//GEN-END:variables
}
