/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Customer;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Elvin
 */
public class CustomerChange extends javax.swing.JInternalFrame {
    String DOB = "";
    String[] DOB1;
    String str1 = "";
    String str2 = "";
    String str3 = "";
    String str4 = "";
    String str5 = "";
    String str6 = "";
    String str7 = "";
    String str8 = "";
    String str9 = "";
    String str10 = "";
    int option =0;
    int q4=0;
    int q3=0;
    int q2=0;
    int q1 =0;
    int t=0;
    int l =0;
    int x =0;
    int y=0;
    int z=0;
    int q=0;
    int year = Calendar.getInstance().get(Calendar.YEAR);
    int vnr = 0;
    
    /**
     * Creates new form CustomerChange
     */
    public CustomerChange() {
        initComponents();
        initComponents();
        try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
        Statement sqlStatement = con.createStatement();
        ResultSet sqlResult = sqlStatement.executeQuery("SELECT ID FROM Market.Members"))
        {
            
            while(sqlResult.next())
                jComboBox1.addItem(sqlResult.getString(1));
            
        
        }
        catch(SQLException sqlEx)
        {
            JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Customer Change");

        jButton1.setText("Change First Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Change Last Name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Change Address");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Change City");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Change State");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Change Zip Code");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Change DoB");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Change Fee");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Change All");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("City:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("State:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Zip Code:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Date of Birth:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Annual Fee:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setToolTipText("Month");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("/");

        jTextField7.setEditable(false);
        jTextField7.setToolTipText("Day");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("/");

        jTextField8.setEditable(false);
        jTextField8.setToolTipText("Year");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("$");

        jButton10.setText("Enter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Refresh");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Cancel");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel13.setText(vnr + " Changed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, 105, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField8))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButton12)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        option =0;
        if(jComboBox1.getSelectedIndex()== -1 || jComboBox1.getSelectedItem().equals("Select"))
        {
            jTextField1.setText("");
         jTextField1.setEditable(false);
         jTextField2.setText("");
         jTextField2.setEditable(false);
         jTextField3.setText("");
         jTextField3.setEditable(false);
         jTextField4.setText("");
         jTextField4.setEditable(false);
         jTextField5.setText("");
         jTextField5.setEditable(false);
         jTextField6.setText("");
         jTextField6.setEditable(false);
         jTextField7.setText("");
         jTextField7.setEditable(false);
         jTextField8.setText("");
         jTextField8.setEditable(false);
         jTextField9.setText("");
         jTextField9.setEditable(false);
         jTextArea1.setText("");
         jTextArea1.setEditable(false); 
        }
        else
        {
            try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
            Statement sqlStatement = con.createStatement();
            ResultSet sqlResult = sqlStatement.executeQuery("SELECT * FROM Market.Members WHERE ID = '"+ jComboBox1.getSelectedItem() + "'"))
            {
                while(sqlResult.next())
                {
                  jTextField1.setText(sqlResult.getString(2));
                  str1 =sqlResult.getString(2);
                  jTextField2.setText(sqlResult.getString(3));
                   str2 =sqlResult.getString(3);
                  jTextArea1.setText(sqlResult.getString(4));
                   str3 =sqlResult.getString(4);
                  jTextField3.setText(sqlResult.getString(5));
                   str4 =sqlResult.getString(5);
                  jTextField4.setText(sqlResult.getString(6));
                   str5 =sqlResult.getString(6);
                  jTextField5.setText(sqlResult.getString(7));
                   str6 =sqlResult.getString(7);
                  DOB = sqlResult.getString(8);
                  DOB1 = DOB.split("-");
                  jTextField6.setText(DOB1[1]);
                   str7 =DOB1[1];
                  jTextField7.setText(DOB1[2]);
                   str8 =DOB1[2];
                  jTextField8.setText(DOB1[0]);
                   str9 =DOB1[0];
                  jTextField9.setText(sqlResult.getString(9));
                   str10 =sqlResult.getString(9);
                }


            }
            catch(SQLException sqlEx)
            {
                JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        option = 0;
        jComboBox1.removeAllItems();
        
        try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
        Statement sqlStatement = con.createStatement();
        ResultSet sqlResult = sqlStatement.executeQuery("SELECT ID FROM Market.Members"))
        {
            
            while(sqlResult.next())
                jComboBox1.addItem(sqlResult.getString(1));
            
        
        }
        catch(SQLException sqlEx)
        {
            JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        jComboBox1.setSelectedIndex(-1);
        jTextField1.setText("");
        jTextField1.setEditable(false);
        jTextField2.setText("");
        jTextField2.setEditable(false);
        jTextField3.setText("");
        jTextField3.setEditable(false);
        jTextField4.setText("");
        jTextField4.setEditable(false);
        jTextField5.setText("");
        jTextField5.setEditable(false);
        jTextField6.setText("");
        jTextField6.setEditable(false);
        jTextField7.setText("");
        jTextField7.setEditable(false);
        jTextField8.setText("");
        jTextField8.setEditable(false);
        jTextField9.setText("");
        jTextField9.setEditable(false);
        jTextArea1.setText("");
        jTextArea1.setEditable(false);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        option=1;
        jTextField1.setEditable(true);
        jTextField1.setText("");
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        option =9;
        jTextField1.setEditable(true);
        jTextField1.setText("");
        jTextField2.setEditable(true);
        jTextField2.setText("");
        jTextField3.setEditable(true);
        jTextField3.setText("");
        jTextField4.setEditable(true);
        jTextField4.setText("");
        jTextField5.setEditable(true);
        jTextField5.setText("");
        jTextField6.setEditable(true);
        jTextField6.setText("");
        jTextField7.setEditable(true);
        jTextField7.setText("");
        jTextField8.setEditable(true);
        jTextField8.setText("");
        jTextField9.setEditable(true);
        jTextField9.setText("");
        jTextArea1.setEditable(true);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        option =2;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(true);
        jTextField2.setText("");
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        option =3;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(true);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        option =4;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(true);
        jTextField3.setText("");
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        option =5;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(true);
        jTextField4.setText("");
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        option =6;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(true);
        jTextField5.setText("");
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        option =7;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(true);
        jTextField6.setText("");
        jTextField7.setEditable(true);
        jTextField7.setText("");
        jTextField8.setEditable(true);
        jTextField8.setText("");
        jTextField9.setEditable(false);
        jTextField9.setText(str10);
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        option =8;
        jTextField1.setEditable(false);
        jTextField1.setText(str1);
        jTextField2.setEditable(false);
        jTextField2.setText(str2);
        jTextField3.setEditable(false);
        jTextField3.setText(str4);
        jTextField4.setEditable(false);
        jTextField4.setText(str5);
        jTextField5.setEditable(false);
        jTextField5.setText(str6);
        jTextField6.setEditable(false);
        jTextField6.setText(str7);
        jTextField7.setEditable(false);
        jTextField7.setText(str8);
        jTextField8.setEditable(false);
        jTextField8.setText(str9);
        jTextField9.setEditable(true);
        jTextField9.setText("");
        jTextArea1.setEditable(false);
        jTextArea1.setText(str3);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        vnr = 0;
        jLabel13.setText(vnr + " Changed");
        option = 0;
        jTextField1.setText("");
        jTextField1.setEditable(false);
        jTextField2.setText("");
        jTextField2.setEditable(false);
        jTextField3.setText("");
        jTextField3.setEditable(false);
        jTextField4.setText("");
        jTextField4.setEditable(false);
        jTextField5.setText("");
        jTextField5.setEditable(false);
        jTextField6.setText("");
        jTextField6.setEditable(false);
        jTextField7.setText("");
        jTextField7.setEditable(false);
        jTextField8.setText("");
        jTextField8.setEditable(false);
        jTextField9.setText("");
        jTextField9.setEditable(false);
        jTextArea1.setText("");
        jTextArea1.setEditable(false);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c9 = evt.getKeyChar();
        if(c9 == KeyEvent.VK_BACK_SPACE)
        {
            q4--;
            if(q4 < 0)
                q4=0;
        }
        else if(q4 < 50)
        {
            
            q4++;
        }
        else if (q4 >= 50)
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c8 = evt.getKeyChar();
        if(c8 == KeyEvent.VK_BACK_SPACE)
        {
            q3--;
            if(q3 < 0)
                q3=0;
        }
        else if(q3 < 50)
        {
            
            q3++;
        }
        else if (q3 >= 50)
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
         char c6 = evt.getKeyChar();
        if(c6 == KeyEvent.VK_BACK_SPACE)
        {
            q2--;
            if(q2 < 0)
                q2=0;
        }
        else if(q2 < 150)
        {
            
            q2++;
        }
        else if (q2 >= 150)
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
         char c5 = evt.getKeyChar();
        if(c5 == KeyEvent.VK_BACK_SPACE)
        {
            q1--;
            if(q1 < 0)
                q1=0;
        }
        else if(q1 < 50)
        {
            
            q1++;
        }
        else if (q1 >= 50)
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
         char c4 = evt.getKeyChar();
        if(c4 == KeyEvent.VK_BACK_SPACE)
        {
            q--;
            if(q < 0)
                q=0;
        }
        else if(q < 2)
        {
            if(!(Character.isLetter(c4) || (c4 == KeyEvent.VK_BACK_SPACE) || c4 == KeyEvent.VK_DELETE))
            {
                getToolkit().beep();
                evt.consume();
            }
            else
            q++;
        }
        else if (q >= 2)
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            l--;
            if(l < 0)
                l=0;
        }
        if(l < 5)
        {
            if (Character.isDigit(c))
            {
                l++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            t--;
            if(t < 0)
                t=0;
        }
        if(t < 7)
        {
            if (Character.isDigit(c)|| c == '.')
            {
                t++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        
        if(jComboBox1.getSelectedIndex() == -1 || jComboBox1.getSelectedItem() == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select an ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(option ==0)
        {
            JOptionPane.showMessageDialog(null, "Nothing has been changed", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextField1.getText().trim().equals("")||jTextField2.getText().trim().equals("")||jTextField3.getText().trim().equals("")||jTextField4.getText().trim().equals("")||jTextField5.getText().trim().equals("")||
                jTextField6.getText().trim().equals("")||jTextField7.getText().trim().equals("")||jTextField8.getText().trim().equals("")||jTextField9.getText().trim().equals("")||
                jTextArea1.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
         else if (Integer.parseInt(jTextField6.getText()) <= 0 ||Integer.parseInt(jTextField7.getText()) <= 0 ||Integer.parseInt(jTextField8.getText()) <= 0 || Double.parseDouble(jTextField9.getText()) <= 0 )
        {
            JOptionPane.showMessageDialog(null, "DOB and Annual Fee must be greater than 0", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (Integer.parseInt(jTextField6.getText()) > 12 && Integer.parseInt(jTextField7.getText()) > 31)
        {
            JOptionPane.showMessageDialog(null, "Invalid DOB: Check Month and Date", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(Integer.parseInt(jTextField8.getText()) > year-15)
        {
            JOptionPane.showMessageDialog(null, "Invalid DOB: Needs to be at least 15 years old", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
         {
            if(option == 1)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET firstName = '" + jTextField1.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 2)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET lastName = '" + jTextField2.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 3)
            {
              try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET address = '" + jTextArea1.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0;   
            }
            else if(option == 4)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET city = '" + jTextField3.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 5)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET state = '" + jTextField4.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 6)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET zipCode = '" + jTextField5.getText() +"' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 7)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET dob = '" + jTextField8.getText() +"-"+jTextField6.getText()+"-"+jTextField7.getText()+" ' WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
            else if(option == 8)
            {
              try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET annualFee = " + jTextField9.getText() +" WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0;   
            }
            else if(option == 9)
            {
                try
                   {
                   Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                   Statement sqlStatement = con.createStatement();
                   sqlStatement.executeUpdate("UPDATE Market.Members SET firstName = '" + jTextField1.getText() +"', lastName = '"+jTextField2.getText()+"', address = '"+jTextArea1.getText()+"', city = '"+jTextField3.getText()+"', state = '"+jTextField4.getText()+"', zipCode = '"+
                           jTextField5.getText()+"', dob = '"+ jTextField8.getText() +"-"+jTextField6.getText()+"-"+jTextField7.getText()+"', annualFee = " + jTextField9.getText() +" WHERE Id = '" + jComboBox1.getSelectedItem()+ "'");
                   sqlStatement.close();
                   vnr++;
                   }
                   catch(SQLException sqlEx)
                   {
                       JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                   }
                jComboBox1.setSelectedIndex(-1);
                jTextField1.setText("");
                jTextField1.setEditable(false);
                jTextField2.setText("");
                jTextField2.setEditable(false);
                jTextField3.setText("");
                jTextField3.setEditable(false);
                jTextField4.setText("");
                jTextField4.setEditable(false);
                jTextField5.setText("");
                jTextField5.setEditable(false);
                jTextField6.setText("");
                jTextField6.setEditable(false);
                jTextField7.setText("");
                jTextField7.setEditable(false);
                jTextField8.setText("");
                jTextField8.setEditable(false);
                jTextField9.setText("");
                jTextField9.setEditable(false);
                jTextArea1.setText("");
                jTextArea1.setEditable(false);
                t = 0;
                x = 0;
                y = 0;
                z = 0;
                l =0;
                q=0;
                q1 = 0;
                q2 = 0;
                q3 =0;
                q4 = 0;
                option = 0; 
            }
           
         }
        jLabel13.setText(vnr + " Changed");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            x--;
            if(x < 0)
                x=0;
        }
        if(x < 2)
        {
            if (Character.isDigit(c))
            {
                x++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            y--;
            if(y < 0)
                y=0;
        }
        if(y < 2)
        {
            if (Character.isDigit(c))
            {
                y++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_BACK_SPACE)
        {
            z--;
            if(z < 0)
                z=0;
        }
        if(z < 4)
        {
            if (Character.isDigit(c))
            {
                z++;
            }
            else if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE))
             {
                 getToolkit().beep();
                 evt.consume();
             }
        }
        else
        {
            getToolkit().beep();
            evt.consume();
             
        }
    }//GEN-LAST:event_jTextField8KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
