/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import java.io.IOException;
import java.util.Scanner;                       
import java.io.FileNotFoundException;           
import java.lang.SecurityException;             
import java.nio.file.Paths;                     
import java.io.IOException;                     
import javax.swing.*; 
import java.util.InputMismatchException;
import java.util.Formatter;
import java.util.FormatterClosedException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author Elvin
 */
public class MainReport extends javax.swing.JDialog {
private static Formatter SummarizedReport, DetailedReport;

    /**
     * Creates new form MainReport
     */
    public MainReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       System.out.println();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory Report");
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("It is suggested that you create either a Summarized Report or Detailed Report before selecting any of the views. If you don't create a Summarized Report or Detailed Report, the view will only show outdated information from the last time it was updated.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Summarized");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Both");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Detailed");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Detailed");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Summarized");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("~Create~");

        jLabel2.setText("~View~");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
        Runtime rt=Runtime.getRuntime();
        String path = Paths.get(".").toAbsolutePath().normalize().toString();
        String file=path+"\\SummarizedReport.txt";
        Process p=rt.exec("Notepad " + file);
        }
        catch(IOException ex)
        {
            jTextArea1.setText("There was an error opening the file.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row1 = 1;
        int row2 =1;
        int row3 =1;
        try
        {            
           SummarizedReport = new Formatter("SummarizedReport.txt");
           SummarizedReport.format("******Summarized Report*****%n%n");
           
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT COUNT(Id) AS Total FROM Market.Store"))
                {

                    while(sqlResult.next())
                        SummarizedReport.format("Total number of stores: "+sqlResult.getString(1));


                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
                
                SummarizedReport.format("%nID:%n");
                
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT Id FROM Market.Store ORDER BY Id"))
                {

                    while(sqlResult.next())
                    {
                        SummarizedReport.format(row1+") "+sqlResult.getString(1)+"%n");
                    row1++;
                    }

                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
                
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT COUNT(Number) AS Total FROM Market.Parts"))
                {

                    while(sqlResult.next())
                        SummarizedReport.format("%n%nTotal number of parts: "+sqlResult.getString(1));


                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
                
                SummarizedReport.format("%nNumber:%n");
                
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT Number FROM Market.Parts ORDER BY Number"))
                {

                    while(sqlResult.next())
                    {
                        SummarizedReport.format(row2+") "+sqlResult.getString(1)+"%n");
                        row2++;
                    }


                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
                
           SummarizedReport.flush();
           SummarizedReport.close();
           jTextArea1.setText("Summarized report has been created.");
        }
        catch(FileNotFoundException fileEx)
        {
            JOptionPane.showMessageDialog(null, "Error opening file.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch(SecurityException securityEX)
        {
            JOptionPane.showMessageDialog(null, "Writing permission denied", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch(FormatterClosedException formatterEx)
        {
            JOptionPane.showMessageDialog(null, "Error writing to file.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try{
        Runtime rt=Runtime.getRuntime();
       String path = Paths.get(".").toAbsolutePath().normalize().toString();
        String file=path+"\\DetailedReport.txt";
        Process p=rt.exec("Notepad " + file);
        }
        catch(IOException ex)
        {
            jTextArea1.setText("There was an Error opening the file.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
        jButton3.doClick();
        jTextArea1.setText("Both Summarized and Detailed Reports have been created.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row1 = 1;
        int row2 = 1;
        int row3 = 1;
        try
        {            
           SummarizedReport = new Formatter("DetailedReport.txt");
           SummarizedReport.format("******Detailed Report*****%n%n");
                
                SummarizedReport.format("%nStores:%n");
                
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT Id FROM Market.Store ORDER BY Id"))
                {

                    while(sqlResult.next())
                    {
                        SummarizedReport.format(row1+") "+sqlResult.getString(1)+"%n");
                    row1++;
                    }

                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
                 
                 SummarizedReport.format("%n%nParts:%n");
                try(Connection con = DriverManager.getConnection(Database.Database.databaseInfo, Database.Database.databaseUsername, Database.Database.databasePassword);
                Statement sqlStatement = con.createStatement();
                ResultSet sqlResult = sqlStatement.executeQuery("SELECT * FROM Market.Parts ORDER BY Number"))
                {

                    while(sqlResult.next())
                    {
                        SummarizedReport.format(row2+") "+sqlResult.getString(1)+"%n");
                        SummarizedReport.format("Name: "+sqlResult.getString(2)+"%n");
                        SummarizedReport.format("onHand: "+ sqlResult.getString(4)+"%n");
                        SummarizedReport.format("Price: $"+sqlResult.getString(3)+"%n%n");
                    row2++;
                    }

                }
                catch(SQLException sqlEx)
                {
                    JOptionPane.showMessageDialog(null, sqlEx.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }

             
           SummarizedReport.flush();
           SummarizedReport.close();
           jTextArea1.setText("Detailed report has been created.");
        }
        catch(FileNotFoundException fileEx)
        {
            JOptionPane.showMessageDialog(null, "Error opening file.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch(SecurityException securityEX)
        {
            JOptionPane.showMessageDialog(null, "Writing permission denied", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        catch(FormatterClosedException formatterEx)
        {
            JOptionPane.showMessageDialog(null, "Error writing to file.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainReport dialog = new MainReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
